name: "Proofread .md files for syntax or style issues"

on:
  pull_request:
    branches:
    - main

jobs:
  proselint:
    name: run proselint
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - run: pip install proselint
    - run: proselint index.md
        
      
