name: "Proofread .md files for syntax or style issues"

on:
  pull_request:
    branches:
    - main

jobs:
  proselint:
    name: run proselint
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: install proselint
        run: pip install proselint
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: run proselint on markdown
        run: find . -name "*.md" | xargs proselint
        
      
